version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    container_name: gama_postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: gama

    admin_postgres:
      image: adminer
      container_name: gama_admin_postgres
      ports:
        - 9081:8080
      depends_on:
        - postgres
